# Generated by Django 4.2.9 on 2026-02-04 07:08

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('admin', 'Admin')], default='citizen', max_length=10)),
                ('phone_number', models.CharField(help_text='10-digit mobile number', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits starting with 6-9', regex='^[6-9]\\d{9}$')])),
                ('aadhar_number', models.CharField(blank=True, help_text='12-digit Aadhar number', max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhar must be exactly 12 digits', regex='^\\d{12}$')])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(help_text='Complete address')),
                ('village', models.CharField(default='Model Village', max_length=100)),
                ('taluka', models.CharField(default='Model Taluka', max_length=100)),
                ('district', models.CharField(default='Model District', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('pincode', models.CharField(help_text='6-digit pincode', max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be 6 digits', regex='^\\d{6}$')])),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='profile_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('application_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('death_certificate', 'Death Certificate'), ('income_certificate', 'Income Certificate'), ('water_tax', 'Water Tax'), ('house_tax', 'House Tax')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='IncomeCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('father_husband_name', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('income_source', models.CharField(choices=[('agriculture', 'Agriculture'), ('business', 'Business'), ('salary', 'Salary/Employment'), ('pension', 'Pension'), ('other', 'Other')], max_length=20)),
                ('income_details', models.TextField(help_text='Detailed description of income sources')),
                ('purpose_of_certificate', models.TextField(help_text='Why do you need this certificate?')),
                ('residential_address', models.TextField()),
                ('income_proof', models.FileField(help_text='Salary slip, Form 16, or other income proof', upload_to='income_certificates/income_proof/')),
                ('id_proof', models.FileField(help_text='Aadhar or other ID proof', upload_to='income_certificates/id_proof/')),
                ('ration_card', models.FileField(blank=True, help_text='Ration card (if available)', null=True, upload_to='income_certificates/ration_card/')),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income_certificate', to='portal_app.application')),
            ],
            options={
                'verbose_name': 'Income Certificate',
                'verbose_name_plural': 'Income Certificates',
                'ordering': ['-application__applied_date'],
            },
        ),
        migrations.CreateModel(
            name='DeathCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_name', models.CharField(max_length=200)),
                ('deceased_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('deceased_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date_of_death', models.DateField()),
                ('place_of_death', models.CharField(max_length=200)),
                ('cause_of_death', models.TextField()),
                ('informant_name', models.CharField(max_length=200)),
                ('informant_relation', models.CharField(max_length=100)),
                ('informant_phone', models.CharField(max_length=10)),
                ('permanent_address', models.TextField()),
                ('hospital_certificate', models.FileField(blank=True, help_text='Hospital/Doctor certificate or Panchnama', null=True, upload_to='death_certificates/hospital/')),
                ('deceased_id_proof', models.FileField(help_text="Deceased person's ID proof", upload_to='death_certificates/id_proof/')),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='death_certificate', to='portal_app.application')),
            ],
            options={
                'verbose_name': 'Death Certificate',
                'verbose_name_plural': 'Death Certificates',
                'ordering': ['-application__applied_date'],
            },
        ),
        migrations.CreateModel(
            name='BirthCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=200)),
                ('child_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('father_aadhar', models.CharField(blank=True, max_length=12)),
                ('mother_name', models.CharField(max_length=200)),
                ('mother_aadhar', models.CharField(blank=True, max_length=12)),
                ('permanent_address', models.TextField()),
                ('hospital_certificate', models.FileField(help_text='Hospital/Doctor certificate', upload_to='birth_certificates/hospital/')),
                ('parents_id_proof', models.FileField(help_text='Parents ID proof', upload_to='birth_certificates/id_proof/')),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birth_certificate', to='portal_app.application')),
            ],
            options={
                'verbose_name': 'Birth Certificate',
                'verbose_name_plural': 'Birth Certificates',
                'ordering': ['-application__applied_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=15)),
                ('new_status', models.CharField(max_length=15)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='portal_app.application')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('water_tax', 'Water Tax'), ('house_tax', 'House Tax')], max_length=15)),
                ('property_number', models.CharField(max_length=50)),
                ('property_address', models.TextField()),
                ('property_area_sqft', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('financial_year', models.CharField(help_text='e.g., 2025-26', max_length=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('online', 'Online'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('dd', 'Demand Draft')], max_length=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('property_document', models.FileField(blank=True, help_text='Property ownership proof', null=True, upload_to='tax_payments/property_docs/')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_payment', to='portal_app.application')),
            ],
            options={
                'verbose_name': 'Tax Payment',
                'verbose_name_plural': 'Tax Payments',
                'ordering': ['-application__applied_date'],
                'indexes': [models.Index(fields=['property_number'], name='portal_app__propert_3bcc0d_idx'), models.Index(fields=['payment_status'], name='portal_app__payment_b1f012_idx')],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('water_supply', 'Water Supply'), ('electricity', 'Electricity'), ('road', 'Road & Infrastructure'), ('sanitation', 'Sanitation'), ('street_light', 'Street Light'), ('drainage', 'Drainage'), ('waste_management', 'Waste Management'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('location', models.TextField(help_text='Location of the issue')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('complaint_photo', models.ImageField(blank=True, help_text='Photo evidence of the issue', null=True, upload_to='complaints/photos/')),
                ('filed_date', models.DateTimeField(auto_now_add=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_remarks', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-filed_date'],
                'indexes': [models.Index(fields=['complaint_number'], name='portal_app__complai_dbdc70_idx'), models.Index(fields=['status'], name='portal_app__status_6ab1d0_idx'), models.Index(fields=['complainant', 'status'], name='portal_app__complai_b4b730_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['application_number'], name='portal_app__applica_93f3a8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='portal_app__status_93bfca_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'status'], name='portal_app__applica_3870ec_idx'),
        ),
    ]
