# Generated by Django 4.2.9 on 2026-02-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('staff', 'Panchayat Staff'), ('admin', 'Admin')], default='citizen', max_length=20),
        ),
    ]
