# Generated by Django 4.2.9 on 2026-02-06 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Complaint Created'), ('assigned', 'Assigned to Staff'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('updated', 'Updated'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=20)),
                ('old_value', models.CharField(blank=True, max_length=100, null=True)),
                ('new_value', models.CharField(blank=True, max_length=100, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='portal_app.complaint')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint History',
                'verbose_name_plural': 'Complaint Histories',
                'ordering': ['-performed_at'],
            },
        ),
    ]
