# Generated by Django 4.2.9 on 2026-02-06 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0003_complainthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False, help_text="Whether user's email has been verified via OTP"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='When email was verified', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Account is active only after email verification'),
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address where OTP was sent', max_length=254)),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this OTP has been successfully verified')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this OTP has been used (one-time use)')),
                ('verification_attempts', models.IntegerField(default=0, help_text='Number of verification attempts (max 3)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When OTP was generated')),
                ('expires_at', models.DateTimeField(help_text='When OTP expires (10 minutes from creation)')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When OTP was successfully verified', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email OTP',
                'verbose_name_plural': 'Email OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_verified'], name='portal_app__user_id_949c05_idx'), models.Index(fields=['email', 'otp_code'], name='portal_app__email_fbcb70_idx')],
            },
        ),
    ]
