# Generated by Django 4.2.9 on 2026-02-06 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0004_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can contain letters, numbers, @, dot, plus, minus, and underscore.', regex='^[\\w.@+-]+$')]),
        ),
    ]
