# Generated by Django 4.2.9 on 2026-02-16 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0006_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required. 4-20 characters. Letters, numbers, and underscore only.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be 4-20 characters long and contain only letters, numbers, and underscore.', regex='^[a-zA-Z0-9_]{4,20}$')]),
        ),
    ]
