# Generated by Django 4.2.9 on 2026-03-21

from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def backfill_emailotp_hash(apps, schema_editor):
    EmailOTP = apps.get_model('portal_app', 'EmailOTP')

    for otp in EmailOTP.objects.filter(otp_code_hash__isnull=True).exclude(otp_code=''):
        raw_code = otp.otp_code
        if raw_code and raw_code.isdigit() and len(raw_code) == 6:
            otp.otp_code_hash = make_password(raw_code)
            otp.otp_code = f"****{raw_code[-2:]}"
            otp.save(update_fields=['otp_code_hash', 'otp_code'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0007_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='otp_code_hash',
            field=models.CharField(blank=True, help_text='Hashed OTP value for secure verification', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(help_text='When OTP expires (1 minute from creation)'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp_code',
            field=models.CharField(help_text='Masked OTP code', max_length=6),
        ),
        migrations.RunPython(backfill_emailotp_hash, noop_reverse),
    ]
