# Generated by Django 4.2.9 on 2026-03-21 04:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0008_emailotp_secure_storage_and_expiry_update'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='WaterBill',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('connection_number', models.CharField(max_length=30)),
                        ('bill_month', models.CharField(help_text='Format: YYYY-MM', max_length=7)),
                        ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                        ('due_date', models.DateField()),
                        ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                        ('transaction_id', models.CharField(blank=True, max_length=120)),
                        ('generated_at', models.DateTimeField(auto_now_add=True)),
                        ('paid_at', models.DateTimeField(blank=True, null=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_bills', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Water Bill',
                        'verbose_name_plural': 'Water Bills',
                        'ordering': ['-generated_at'],
                        'indexes': [models.Index(fields=['user', 'payment_status'], name='portal_app__user_id_2612f8_idx'), models.Index(fields=['connection_number'], name='portal_app__connect_4eb712_idx'), models.Index(fields=['bill_month'], name='portal_app__bill_mo_3b779e_idx')],
                        'unique_together': {('user', 'connection_number', 'bill_month')},
                    },
                ),
            ],
        ),
        migrations.CreateModel(
            name='PropertyTaxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_number', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=200)),
                ('property_address', models.TextField()),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=20)),
                ('built_up_area_sqft', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_rate_per_sqft', models.DecimalField(decimal_places=2, default=1.5, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_year', models.CharField(help_text='Format: YYYY-YY', max_length=9)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_tax_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Tax Record',
                'verbose_name_plural': 'Property Tax Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'payment_status'], name='portal_app__user_id_ddf90d_idx'), models.Index(fields=['property_number'], name='portal_app__propert_e3ff7e_idx'), models.Index(fields=['tax_year'], name='portal_app__tax_yea_84d65a_idx')],
                'unique_together': {('user', 'property_number', 'tax_year')},
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='ElectricityBill',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('consumer_number', models.CharField(max_length=30)),
                        ('bill_month', models.CharField(help_text='Format: YYYY-MM', max_length=7)),
                        ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                        ('due_date', models.DateField()),
                        ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                        ('transaction_id', models.CharField(blank=True, max_length=120)),
                        ('generated_at', models.DateTimeField(auto_now_add=True)),
                        ('paid_at', models.DateTimeField(blank=True, null=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_bills', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Electricity Bill',
                        'verbose_name_plural': 'Electricity Bills',
                        'ordering': ['-generated_at'],
                        'indexes': [models.Index(fields=['user', 'payment_status'], name='portal_app__user_id_1b1c9c_idx'), models.Index(fields=['consumer_number'], name='portal_app__consume_20ae39_idx'), models.Index(fields=['bill_month'], name='portal_app__bill_mo_491ee0_idx')],
                        'unique_together': {('user', 'consumer_number', 'bill_month')},
                    },
                ),
            ],
        ),
    ]
