# Generated by Django 4.2.9 on 2026-03-21 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0009_waterbill_propertytaxrecord_electricitybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='approval_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='certificate_pdf',
            field=models.FileField(blank=True, help_text='System-generated certificate or approval PDF', null=True, upload_to='certificates/generated/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='application',
            name='email_delivery_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='email_delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='complaint',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_record', to='portal_app.application'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('death_certificate', 'Death Certificate'), ('income_certificate', 'Income Certificate'), ('complaint_submission', 'Complaint Submission'), ('bill_request', 'Bill Related Request'), ('water_tax', 'Water Tax'), ('house_tax', 'House Tax')], max_length=20),
        ),
        migrations.CreateModel(
            name='BillRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('electricity', 'Electricity Bill'), ('water', 'Water Bill'), ('property_tax', 'Property Tax'), ('other', 'Other Bill Request')], max_length=20)),
                ('account_or_consumer_number', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='bill_requests/attachments/')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill_request', to='portal_app.application')),
            ],
            options={
                'verbose_name': 'Bill Request',
                'verbose_name_plural': 'Bill Requests',
                'ordering': ['-application__applied_date'],
            },
        ),
    ]
