# Generated by Django 4.2.9 on 2026-03-23 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0011_normalize_legacy_bill_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('application_submitted', 'Application Submitted'), ('application_updated', 'Application Updated'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('complaint_submitted', 'Complaint Submitted'), ('complaint_updated', 'Complaint Updated'), ('payment_recorded', 'Payment Recorded'), ('document_downloaded', 'Document Downloaded'), ('login', 'Login'), ('other', 'Other')], default='other', max_length=40)),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='portal_app.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='portal_app__user_id_4a32ec_idx'), models.Index(fields=['action'], name='portal_app__action_65e97f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('application', 'Application'), ('certificate', 'Certificate'), ('complaint', 'Complaint'), ('bill', 'Bill'), ('system', 'System')], default='system', max_length=20)),
                ('target_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='portal_app__recipie_db088d_idx'), models.Index(fields=['created_at'], name='portal_app__created_ed3b88_idx')],
            },
        ),
    ]
