# Generated by Django 4.2.9 on 2026-04-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0013_realign_notification_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload a profile photo', null=True, upload_to='profile_photos/'),
        ),
    ]
