# Generated by Django 4.2.9 on 2026-04-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0014_alter_customuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Full name of the user', max_length=255),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('application_submitted', 'Application Submitted'), ('application_updated', 'Application Updated'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('complaint_submitted', 'Complaint Submitted'), ('complaint_updated', 'Complaint Updated'), ('payment_recorded', 'Payment Recorded'), ('document_downloaded', 'Document Downloaded'), ('profile_updated', 'Profile Updated'), ('password_changed', 'Password Changed'), ('account_deleted', 'Account Deleted'), ('user_managed', 'User Managed'), ('login', 'Login'), ('other', 'Other')], default='other', max_length=40),
        ),
    ]
