# Generated by Django 4.2.9 on 2026-04-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0015_customuser_name_alter_useractivity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', help_text='Gender declared by user', max_length=10),
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('aadhar_number', models.CharField(blank=True, default='', max_length=12)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='pending_profiles/')),
                ('password_hash', models.CharField(max_length=128)),
                ('otp_code_hash', models.CharField(max_length=128)),
                ('otp_expires_at', models.DateTimeField()),
                ('otp_attempts', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_otp_sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='portal_app__email_c19b14_idx'), models.Index(fields=['phone_number', 'created_at'], name='portal_app__phone_n_9d6dd9_idx')],
            },
        ),
    ]
