# Generated by Django 4.2.9 on 2026-04-17 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0016_customuser_gender_pendingregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be 4-20 characters long and contain only letters, numbers, and underscore.', regex='^[a-zA-Z0-9_]{4,20}$')]),
        ),
    ]
